name: wake-up

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  call-sleeping-process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      - name: Install requests
        run: pip install requests
      - name: Run code
        run: |
          python call_sleeping.py